### ISSUE TITLE
mapTwoWayState apply filter

### ISSUE THREAD

**Issue by ecmel** [spyfu/spyfu-vuex-helpers#5]
Thank you for great helpers.

Is it possible to add ability to pass a filter to mapTwoWayState?

**Comment by scottbedard** [comment]
Hi, glad you like the helpers! Could you elaborate on what you mean though? I'm having trouble understanding what you're asking without more details or example code.

**Comment by ecmel** [comment]
Hi,

I need to modify passed value to getters and setters, like:

```
 ...mapTwoWayState({
        amount: { key: 'amount', mutation: 'setAmount', get: someFilterFunction, set: someOtherFilterFunction } 
      })

```

Filter function signature can be standard Vue.js filter function like:

```
function trim(val) {
  return val ? val.trim() : ''
}
```

Both get and set should be optional.

**Comment by scottbedard** [comment]
Ok, I see what you're asking now. At that point though, if we've already defined a getter and setter function, why not just use a regular computed property? I'm not sure I see the benefit of using a helper in this situation.
